# Generated by Django 4.0.2 on 2022-02-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='name',
            new_name='user_id',
        ),
    ]
