# Generated by Django 4.0.2 on 2022-02-27 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_rename_name_seller_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='platform',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portal.platform'),
            preserve_default=False,
        ),
    ]
